### ISSUE TITLE
Broken Enchantments [Bug]: 

### ISSUE THREAD

**Issue by SudoSpider** [Mrbysco/EnchantableBlocks#1]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.2.32

### Minecraft version

1.20.1

### Mod version

0.0.2

### Java version

Java 8 Update 411

### Issue Description

All enchantments for the Blast furnace with the exception of glintless do not work, they do not apply their effect.
All tiers of fuel efficiency are broken and rapidly consume your fuel.
Preservation can be applied to more then a crafting table.
Enchanted campfires have a broken flame texture when placed.
Enchanted magma blocks turn into a fake beacon when placed.
All Bed enchantments seem to have no effect (could just be me).
Enchanted beacons cannot open the beacon gui.
Beehive Enchantments haven't been tested, I don't really know how to use it.

![Broken beacons and campfires](https://github.com/Mrbysco/EnchantableBlocks/assets/25124370/1b24083a-149e-4e72-a12a-260f26f0f9aa)

Mods included with testing: 
JEI 15.3.0.4
Jade 11.8.0
Jade Addons 5.2.2

**Comment by Mrbysco** [comment]
- [x] Blast Furnace enchantments function again

**Comment by Mrbysco** [comment]
- [x] Fixed enchanted Soul Campfire and Magma Block turning into the wrong enchanted block variant

**Comment by Mrbysco** [comment]
- [x] Fix Enchanted Bed not realizing that it is enchanted

**Comment by Mrbysco** [comment]
- [x] Fix being unable to open the Enchanted Beacon GUI
