### ISSUE TITLE
[Bug]: Enchanted hoppers dont work

### ISSUE THREAD

**Issue by Saereth** [Mrbysco/EnchantableBlocks#2]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

20.4.234

### Minecraft version

1.20.4

### Mod version

EnchantableBlocks-1.20.4-0.0.4.jar

### Java version

j17

### Issue Description

Enchanted hopper dont seem to be transfering any items. Using efficiency 3 hopper into a vanilla furnace transfers nothing. Even glintless enchanted only has the same issue. Regular hopper working fine.

Seems to work fine on chests though...
<img width="1018" alt="image" src="https://github.com/Mrbysco/EnchantableBlocks/assets/9200909/d51d366c-5d8d-44ae-aac4-c2dad010e0df">

### Additional Information

Also seems to work fine from the side and bottom just not inputting
<img width="592" alt="image" src="https://github.com/Mrbysco/EnchantableBlocks/assets/9200909/2195cab3-0694-4028-9c3b-2f91c1c9b44d">

**Comment by Mrbysco** [comment]
Fixed in-dev and a new build is being generated
