### ISSUE TITLE
[Bug]: Solar radiance does not register dimensions

### ISSUE THREAD

**Issue by Ch4rm-Quark** [Mrbysco/EnchantableBlocks#6]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

20.4.237 NeoForge

### Minecraft version

1.20.4

### Mod version

0.0.13

### Java version

J8 update 321

### Issue Description

curnace/blast furnace/smoker does not process when exposed to open sky with cookable blocks inside while in dimensions other than overworld. FTB neotech JAVD void dimension specifically, which is set to be permanent daytime.

**Comment by Mrbysco** [comment]
I'll look into it. All I do is check the vanilla method for checking if it has sky access

**Comment by sciwhiz12** [comment]
Seems to be an 'issue' with how `Level#isDay` determines if it's day in a dimension. 

That method returns `true` when the darkness of the sky is, for lack of a better term, not high enough (based on `Level#skyDarken`), and if the dimension's type does not have a fixed time. For the void dimension added by the Just Another Void Dimension mod, it does [fix the time to noon](https://github.com/nanite/JAVD/blob/4528332459eda4a46fa1c6cb8417f3e7f025fbf3/forge/src/generated/resources/data/javd/dimension_type/mining.json#L6) in the dimension type, so the [`Level#isDay` check for the enchanted furnace](https://github.com/Mrbysco/EnchantableBlocks/blob/b4719ecd93578111a3635cb01d78fbfd5b2e0033/src/main/java/com/mrbysco/enchantableblocks/block/blockentity/furnace/AbstractEnchantedFurnaceBlockEntity.java#L63) fails in those dimensions.

Perhaps an adequate fix there is to replicate the sky darkness check from `Level#isDay` if the dimension has a fixed time? (While keeping in the use of `Level#isDay`, in case some other implementation of `Level` from another mod or elsewhere overrides it.)
